# For more info on HTTP files go to https://aka.ms/vs/httpfile

@server=localhost:7395

# Ping
GET https://{{server}}

###

POST https://{{server}}/accounts/signup
Content-Type: application/json

{
  "name": "Test User",
  "nickname": "tstusr",
  "email": "user@test.com"
}

###
